### ISSUE TITLE
doi button overlaps with bold button when SBS is enabled in SOX

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/CitationHelperForSE#3] opened 2018-09-06 16:04 UTC
Currently it looks like that the button is looking a bit weird:

![unbenannt3](https://user-images.githubusercontent.com/19774680/45170015-2a583200-b1ff-11e8-9787-60c7a46a3837.PNG)

For reference: [chat @ SE](https://chat.stackexchange.com/transcript/message/46616177#46616177)

With Side by side editing enabled under SOX.

**Comment by polyluxus** [comment] 2018-09-06 16:28
I deactivated SOX, killed chrome, restarted, only the helper running, still looks the same. (Caching?)

**Comment by GaurangTandon** [comment] 2018-09-18 17:50
Yep, I can't reproduce it either :( Sorry, but I will need to close the issue. If you can get to reproduce it again, please let me know. Thanks.

**Closed by GaurangTandon** 2018-09-18 17:50 UTC
