### ISSUE TITLE
incorrect capitalisation of author names where surname has multiple words

### ISSUE THREAD

**Issue by yongrenjie** [GaurangTandon/CitationHelperForSE#5] opened 2018-09-18 08:33 UTC
example doi: 10.1039/C5SC03429A

current long output: `Preiß, S.; Melomedov, J.; Wünsche von leupoldt, A.; Heinze, K. Gold(iii) tetraarylporphyrin amino acid derivatives: ligand or metal centred redox chemistry?. *Chem. Sci.* **2016,** *7* (1), 596–610. [DOI: 10.1039/C5SC03429A](https://doi.org/10.1039/C5SC03429A).`

should be: `Preiß, S.; Melomedov, J.; Wünsche von Leupoldt, A.; Heinze, K. Gold(III) tetraarylporphyrin amino acid derivatives: ligand or metal centred redox chemistry?. *Chem. Sci.* **2016,** *7* (1), 596–610. [DOI: 10.1039/C5SC03429A](https://doi.org/10.1039/C5SC03429A).`

Technically the `Gold(iii)` in the title is also wrong and should be `Gold(III)`, but that's a separate issue from this, so maybe ignore that for now.

tested with another paper from the same author: 10.1021/ic300929g, issue is also present

**Comment by GaurangTandon** [comment] 2018-09-18 17:35
For now, I have hardcoded fixes for the following two patterns:

1. `von [a-z]` in author names
2. `(i+)` in journal titles

Please verify if the fix works as intended.

**Comment by polyluxus** [comment] 2018-10-01 12:40
Hyphenated names do not work, example: https://doi.org/10.1016/j.jff.2018.07.016

```
1. Beltrán-barrientos, L. M.; Estrada-montoya, C.; Reyes-díaz, R.; Hernández-mendoza, A.; González-córdova, A. F.; Vallejo-córdoba, B. Does gamma-aminobutyric acid have a potential role on the antihypertensive effect of fermented milk with Lactococcus lactis NRRL B-50571? *J. Funct. Foods* **2018,** *48*, 297–301 [DOI: 10.1016/j.jff.2018.07.016](https://doi.org/10.1016/j.jff.2018.07.016).
```

**Comment by GaurangTandon** [comment] 2018-10-01 16:09
Fixed, please check.

**Comment by yongrenjie** [comment] 2018-10-01 16:09
similar issue with 10.1021/jm049082i

`2. Allegretti, M.; Bertini, R.; Cesta, M. C.; Bizzarri, C.; Di Bitondo, R.; Di Cioccio, V.; Galliera, E.; Berdini, V.; Topai, A.; Zampella, G.; Russo, V.; Di Bello, N.; Nano, G.; Nicolini, L.; Locati, M.; Fantucci, P.; Florio, S.; Colotta, F. 2-Arylpropionic CXC Chemokine Receptor 1 (CXCR1) Ligands as Novel Noncompetitive CXCL8 Inhibitors. *J. Med. Chem.* **2005,** *48* (13), 4312–4331. [DOI: 10.1021/jm049082i](https://doi.org/10.1021/jm049082i).`

The surname after "Di" needs to be capitalised as well.

**Comment by GaurangTandon** [comment] 2018-10-01 16:16
I pushed another update. I have been hardcoding the three patterns for now. But I was wondering if there existed a pattern for these capitalizations.

**Comment by polyluxus** [comment] 2018-10-02 08:48
I don't think it is possible to have a catch'em all. This is an internationalisation problem, as it is also described in this SO post: [JavaScript validation issue with international characters](https://stackoverflow.com/q/1073412/3180795). 

I have not had a look at the source, so I can only speculate that you are trying to identify the family name, and then the given names, normalise, and reassemble. A problem, that is much more complex than the one in the linked question. You'll always have some trouble doing it right all the time and I guess the best way to deal with this (unfortunately) is to add exceptions on a case by case basis. There might be cases, where people do not even have a given name (or only one in general), see Academia.se's [I have only one name shown in my ID card. How do I write my name (surname) in research paper or article?](https://academia.stackexchange.com/q/83593/13372)

Maybe it would be worthwhile producing a library for such patterns, which might be easier to maintain.

**Comment by GaurangTandon** [comment] 2018-10-02 13:03
> Maybe it would be worthwhile producing a library for such patterns, which might be easier to maintain.

Good suggestion, please keep reporting more such author name capitalization issues you run into for the time being. When the list becomes substantially large, I might consider spinning it off into its own separate code. Till then, I'm closing this issue.

**Closed by GaurangTandon** 2018-10-02 13:03 UTC
